package(default_visibility = ["//visibility:public"])

py_test(
    name = "auth_test",
    srcs = ["tests/unit/_auth_test.py"],
    main = "tests/unit/_auth_test.py",
    size = "small",
    deps = [
        "//src/python/grpcio:grpcio",
    ],
)
